# This is a basic workflow to help you get started with Actions

name: Release artifact

# Controls when the workflow will run
on: release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Maven Build
        run: mvn package -Dmdep.skip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
         args: target/AdiAuth*.jar
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
